# Generated by Django 4.0.1 on 2022-01-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_profile_image'),
        ('file_manager', '0002_category_is_archived_fileupload_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='uploader_id',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
