# Generated by Django 4.0.1 on 2022-01-25 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_profile_image'),
        ('file_manager', '0006_category_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='last_editor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='category_last_editor', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='last_editor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='fileupload_last_editor', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_creator', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileupload_uploader', to='accounts.user'),
        ),
    ]
