# Generated by Django 4.0.1 on 2022-01-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0007_category_last_editor_fileupload_last_editor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
