# Generated by Django 4.0.1 on 2022-01-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('picture_path', models.CharField(default='default_profile_img.jpg', max_length=200)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
