# Generated by Django 4.0.1 on 2022-01-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_path',
            field=models.CharField(default='accounts/default_profile_img.jpg', max_length=200),
        ),
    ]
