# Generated by Django 4.0.1 on 2022-01-31 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='log_type',
            new_name='log_code',
        ),
    ]
